kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: frontend
  labels:
    app: todonodejs
    name: frontend
spec:
  to:
    kind: Service
    name: prod-frontend
    weight: 100
  wildcardPolicy: None
  host: todo-prod.apps.equeiroz.rhbr-lab.com.br
  path: /todo

